version: "3.9"
services:
  # clickhouse-server:
  #   image: yandex/clickhouse-server
  #   restart: always
  #   ports:
  #     - 34424:34424
  #     - 9000:9000
  #     - 9009:9009
  #     - 8123:8123
  #   volumes:
  #     - ./databases/clickhouse/data:/var/lib/clickhouse
  #   ulimits:
  #     nofile:
  #       soft: 262144
  #       hard: 262144
  mysql:
    restart: always
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      # - ./databases/mysql/conf/my.cnf:/etc/my.cnf
      - ./databases/mysql/logs:/logs
      - ./databases/mysql/data:/var/lib/mysql
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASEL: root
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
  # web:
  #   build: .
  #   depends_on:
  #     - clickhouse-server
  #     - postgres
  #     - redis
  #   ports:
  #     - 20001:20001